name: my-CI

on:
    push:
        branches: master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: Node JS Setup
              uses: actions/setup-node@v2
              with:
                version: 14
            
            - name: Install Dependencies
              run: npm install
            
            - name: Build
              run: npm run build
            
            - name: Deploy Github Pages
              run: |
                git checkout gh-pages || git checkout --orphan gh-pages
                git rm -rf .
                cp -R ./build/* ./
                git add .
                git commit -m "Deployment"
                git push origin gh-pages --force
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}