name: my-CI

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: Node JS Setup
              uses: actions/setup-node@v2
              with:
                version: 20
            
            - name: Install Dependencies
              run: npm install
            
            - name: Build
              run: npm run build
            
            - name: List Build Directory
              run: ls -Ar .

            - name: Set Git User name and Email
              run: |
                git config --global user.name ${{secrets.NAME}}
                git config --global user.email ${{secrets.EMAIL}}

            - name: Deploy Github Pages
              run: |
                ls -Ar .
                git checkout gh-pages || git checkout --orphan gh-pages
                # git rm -rf src public package.json package-lock.json .gitignore node_modules README.md
                find . -not -name 'build' -not -name '.git' -exec rm -rf {} +
                cp -R ./build/* .
                git rm -rf ./build
                git add .
                git commit -m "Deployment"
                git push origin gh-pages
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
